# Generated by Django 2.2.15 on 2020-08-25 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('setor', models.CharField(choices=[('ti', 'Tecnico de Informatica'), ('autorização', 'Autorização'), ('Cobranca', 'Cobrança')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=20)),
                ('cor', models.CharField(choices=[('preto', 'Preto'), ('azul', 'Azul'), ('amarelo', 'Amarelo'), ('branco', 'Branco'), ('prata', 'Prata'), ('vermelho', 'Vermelho')], max_length=20)),
                ('preco', models.FloatField()),
                ('Data', models.DateTimeField()),
                ('Funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unidentis_App.Funcionario')),
            ],
        ),
    ]
